### PR TITLE
Enable sylph to run app with flavor

### LINKED ISSUE #75: Cannot use sylph with flavors
If sylph is run in an app with falvors, the following occurs:

```
Starting Flutter app com.ianum.app
.dev
.alpha in debug mode...
Running "flutter pub get" in ianum_flutter...                       0.8s
Android Debug Bridge version 1.0.41
Version 29.0.1-5644136
Installed as /Users/goncalopalma/Library/Android/sdk/platform-tools/adb
/system/bin/sh: .dev: not found
/system/bin/sh: .alpha: not found
```

As you can see from the multiple lines it went to fetch not only `applicationId` but also `applicationIdSuffix`

Additionally, the project assumes in 
`adb shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true --ez start-paused true "$app_id/$app_id.MainActivity"`

That all applicatuons will:
- have the package name the same as the app id
- Have the same app id in different flavors

This will throw an error since `adb` will not be able to find that activity

### PR DESCRIPTION
**Pull request by Vanethos**
Partial fix for #75 

Enables the user to specify a `flavor` in the `sylph` file:

```
# flavor configuration
flavor: dev
```

### CODE REVIEW

**Comment by mmcc007** [comment]
FYI: other than improving tests, the main change in recent commits is https://github.com/mmcc007/sylph/pull/76/commits/9c16c728d47e72663f6c3ddc2a6f32d7297a3c71, refactoring _buildUploadApp (from https://github.com/mmcc007/sylph/tree/%2375_flavors branch). Should be no functional change.

**Review by mmcc007 — COMMENTED** [review]
flutter build creates build/app/outputs/apk/app.apk by default for the latest build (flavor or no flavor). So switched to using that. 

Also still not able to recreate problem with app_id/package so temporarily removed that code. If you can provide a way to recreate this problem that would be great. 

Confirmed this code works on AWS.

**Comment by Vanethos** [comment]
@mmcc007 I'm terribly sorry, this weekend I did not have the time to do the checks you asked, as soon as I can I'll do that!

**Comment by mmcc007** [comment]
No worries. 

For now, since it seems to be working for android with example/flavors, I might consider that part done (unless you can show otherwise 😀👍).

Will be fixing for ios. When it also works for ios, it should be ready to merge.

**Comment by Vanethos** [comment]
I'm curious, is there something not working atm for iOS?

And if so, do you want to split the work?

**Comment by mmcc007** [comment]
There was a problem with the build that was fixable by tweaking the schemes. Haven't tested on AWS yet. 

Will probably keep on same PR since sylph is designed to always work on both android and ios (unless you think otherwise).

**Comment by Vanethos** [comment]
Nope, I think you are right, having different PRs for fixes would be a nightmare to you.

I'll try to check it this afternoon and see what I can help you with

**Comment by Vanethos** [comment]
@mmcc007 I ran your `test_android.sh` script and it gave me the same error as I had before this PR

```
Starting Flutter app com.ianum.app
.dev
.alpha in debug mode...
Running "flutter pub get" in ianum_flutter...                       1.0s
Android Debug Bridge version 1.0.41
Version 29.0.1-5644136
Installed as /Users/goncalopalma/Library/Android/sdk/platform-tools/adb
/system/bin/sh: .dev: inaccessible or not found
/system/bin/sh: .alpha: inaccessible or not found
```

It is looking for the ids and it tries to start different apps

You removed the possibility of this script accepting the package id, correct?

Because with my script what can be done is:

`sh /path/to/test_android.sh --run-tests test_driver/app_test.dart --package com.ianum.ianumflutter --id com.ianum.app.dev`

And it will run the tests correctly because:
- You gave theapp id: `com.ianum.app.dev`
- You gave the package name: `com.ianum.ianumflutter`

**Comment by Vanethos** [comment]
I also added an `applicationIdSuffix` to the flavors testing and changed the `applicationId` of the app so that it is **different** from the package name of the app

this will make it easier to test on your end!

**Comment by mmcc007** [comment]
Thanks, I have a better idea now of what you are running into. Hopefully I can reproduce the problem and add support.

Sylph runs on both android and ios. And since there are multiple ways to support flavors on both android and ios, it makes sense to pick one for each platform (at least at first to get things working). 

The flavors 'way' I have been working with is based on https://github.com/flutter/flutter/tree/master/dev/integration_tests/flavors.  I ran a test of example/flavors (not including your latest commit) on both android and ios on AWS and it succeeded (using local code changes). I recommend we commit these changes as the default way to support flavors.  

Then can start adding support for additional ways to config flavors. Sylph users can then choose which way they prefer to config flavors that Sylph supports.

So once the 'default way' is supported, can add the way you are configing flavors on android. Does that work for you?

**Comment by Vanethos** [comment]
@mmcc007 well "work for me" is a difficult word since in reality it won't work for me ahahaha. But it makes sense what you are saying.

For me it's more clear if we support all at the same time. Especially because I pushed this PR after Andrea Bizzotto reported the problem of the different application ids for Android. But it's your choice!

At the same time, I'm trying to test things out on iOS but can't run the `test_ios.sh` script because I think there's an argument mismatch (or maybe I'm just sleepy)

**Comment by mmcc007** [comment]
At this point, there is support for flavors (the 'default way'). So could probably merge this PR and create another for 'non-default ways'. Might keep things simpler moving forward. What do you think?

I added-back your config in build.gradle and ran a local flutter drive. Intent went from
```
com.yourcompany.flavors/com.yourcompany.flavors.MainActivity
```
to
```
com.yourcompany.productionpackage.paid/com.yourcompany.flavors.MainActivity
```
So make sense we can add-back your code for handling both use cases on android. Hopefully will not affect iOS.

If running on iOS in CI (since I assume you are not on a mac), some config is necessary (see README .. and can provide support if needed to get working)

Thanks for all the effort btw. It is very helpful.

**Comment by Vanethos** [comment]
@mmcc007 looking at the code for the `test_ios.sh` I see the following:

```
  if [[ -z "$test_path" ]]; then
    echo "Running flutter -v drive --no-build $debug_app_path"
    flutter -v drive --no-build "$debug_app_path"
  else
    echo "Running flutter -v drive --no-build -t $debug_app_path --driver $test_path"
    flutter -v drive --no-build "$debug_app_path" -t "$debug_app_path" --driver "$test_path"
  fi
```

However, `-t` is for the target (`lib/main_dev.dart`) and not for the debug application path

When I removed this argument I could run the tests with the command 

`sh /path/to/sylph/lib/resources/script/test_ios.sh --run-driver test_driver/app.dart`

Note that this is `app.dart` since flutter is going to add the `_test`(as you well know, but I had this error so many times ahahah)

**Comment by Vanethos** [comment]
@mmcc007 you said you added compability to those, but how can you pass them as an argument to the script?

Because as I see it now the script only allows 1 argument, instead of the 3 I put before

**Comment by mmcc007** [comment]
I ran a simple 'flutter drive -v' from the command line to get the intent string.

**Comment by mmcc007** [comment]
Looks like test_ios.sh could use a little cleanup... maybe tomorrow.

**Comment by mmcc007** [comment]
Did u want to merge this PR and create a new one for 'non-default ways' or continue on this PR? It's at a good point right now (since confirmed on AWS). Either way is ok.

**Comment by Vanethos** [comment]
@mmcc007 if you want to merge it go ahead!

My only "issue" with it is that if we want to add the other stuff I'll have to dig up again my old code and put it into the new PR, but it could be a good way to differentiate each issue

**Comment by mmcc007** [comment]
@Vanethos 
This PR turned out to be a little more complex than I had hoped. Though it's looking good now.  It's the old story of 'the devil is in the details' while still trying to manage the complexity and KISS.

I'll probably merge this PR as is (to close out sylph support for the 'default' or 'reference' implementation of flavors).  

You can then create a PR for 'different package names'.

Since I removed the 'different package names' code, feel free to make an empty (almost) PR and I'll copy your code over and we can go from there. 

Since I assume you are not on a mac (right?), I can do some local testing to make sure sylph support for 'different package names' works for iOS. My guess is it should be self-contained in the schemes, etc.. so should not require additional support from sylph (as you originally mentioned). 

How does that sound?

**Comment by Vanethos** [comment]
That sounds perfect with one condition: I can copy the code! I'm here to help you!!!

And I am indeed on a Mac, that's why I told you about the possible mismatch in the iOS test script where apparently the target (which is supposed to be a main.dart file) was being set as a Runner.app file.

And sorry for making this overly complex!

But as I said I tried to make it simple to support my own case (i had a custom fork of sylph but decided to generalize it and do the PR)

Thanks for all the latience! @mmcc007

**Comment by mmcc007** [comment]
Supporting both android and iOS (with code coverage) adds the complexity. But it is worth it.

Great! I will merge this and keep an eye out for the other PR.

Thnx!

**Comment by MarcoAltranDC** [comment]
Are there an ETA when a new release with this feature will be available?

Please let me know if there is a way to run the executable directly through master.

**Comment by mmcc007** [comment]
@MarcoAltranDC run off the master with
```
git clone https://github.com/mmcc007/sylph
pub global activate --source path sylph
```
Sorry for the delay. Will do a release shortly

**Comment by alauk** [comment]
Hi @mmcc007 , 
I'm using 0.7.2 version but does't work for me with flavors. 
The project has 3 flavors (prod, dev and qa). "flavor: dev" was set on sylph.yaml file. 

error log:
```
/system/bin/sh: .dev: not found
/system/bin/sh: .qa: not found
Starting: Intent { act=android.intent.action.RUN flg=0x20000000 pkg=[applicationId] (has extras) }
Error: Activity not started, unable to resolve Intent { act=android.intent.action.RUN flg=0x30000000 pkg=[applicationId] (has extras) }
/system/bin/sh: .dev: not found
/system/bin/sh: .qa/.MainActivity: not found
```
Why is the "qa" flavor logged in test?

NOTE: [applicationId] is from defaultConfig, without ".dev" suffix. 
I replaced applicationId because it's sensitive data

**Comment by mmcc007** [comment]
@alauk 
Please follow the recommended method to implement flavors
(see https://github.com/mmcc007/sylph/issues/75#issuecomment-592919054)

**Pull request merged**
